// import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";

// const poppins = Poppins({ subsets: ["latin"], weights: [100, 200, 300, 400, 500, 600, 700, 800, 900] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
